// ─── TEAM DATA ───────────────────────────────────────────────────────────────
// winner: overall tournament winner probability (%) from XGBoost model
// flag:   ISO 3166-1 alpha-2 code for flagcdn.com
const TEAMS = {
  "England":               { group:"L", rank:4,  winner:9.32,  flag:"gb-eng" },
  "France":                { group:"I", rank:1,  winner:9.02,  flag:"fr"     },
  "Argentina":             { group:"J", rank:3,  winner:8.04,  flag:"ar"     },
  "Spain":                 { group:"H", rank:2,  winner:7.24,  flag:"es"     },
  "Morocco":               { group:"C", rank:8,  winner:6.56,  flag:"ma"     },
  "Brazil":                { group:"C", rank:6,  winner:5.73,  flag:"br"     },
  "Portugal":              { group:"K", rank:5,  winner:4.12,  flag:"pt"     },
  "Germany":               { group:"E", rank:10, winner:4.05,  flag:"de"     },
  "Belgium":               { group:"G", rank:9,  winner:3.48,  flag:"be"     },
  "Uruguay":               { group:"H", rank:17, winner:3.46,  flag:"uy"     },
  "Ecuador":               { group:"E", rank:23, winner:3.22,  flag:"ec"     },
  "Netherlands":           { group:"F", rank:7,  winner:3.11,  flag:"nl"     },
  "Colombia":              { group:"K", rank:13, winner:3.01,  flag:"co"     },
  "Japan":                 { group:"F", rank:18, winner:2.61,  flag:"jp"     },
  "USA":                   { group:"D", rank:16, winner:2.58,  flag:"us"     },
  "Mexico":                { group:"A", rank:15, winner:2.33,  flag:"mx"     },
  "Croatia":               { group:"L", rank:11, winner:2.29,  flag:"hr"     },
  "Switzerland":           { group:"B", rank:19, winner:2.00,  flag:"ch"     },
  "South Korea":           { group:"A", rank:25, winner:1.50,  flag:"kr"     },
  "Senegal":               { group:"I", rank:14, winner:1.34,  flag:"sn"     },
  "Turkey":                { group:"D", rank:22, winner:1.12,  flag:"tr"     },
  "Algeria":               { group:"J", rank:28, winner:1.10,  flag:"dz"     },
  "Egypt":                 { group:"G", rank:29, winner:1.07,  flag:"eg"     },
  "Canada":                { group:"B", rank:30, winner:0.99,  flag:"ca"     },
  "Austria":               { group:"J", rank:24, winner:0.77,  flag:"at"     },
  "Iran":                  { group:"G", rank:21, winner:0.76,  flag:"ir"     },
  "Uzbekistan":            { group:"K", rank:50, winner:0.75,  flag:"uz"     },
  "Tunisia":               { group:"F", rank:44, winner:0.71,  flag:"tn"     },
  "Czech Republic":        { group:"A", rank:41, winner:0.67,  flag:"cz"     },
  "Australia":             { group:"D", rank:27, winner:0.64,  flag:"au"     },
  "Scotland":              { group:"C", rank:43, winner:0.63,  flag:"gb-sct" },
  "DR Congo":              { group:"K", rank:46, winner:0.62,  flag:"cd"     },
  "Paraguay":              { group:"D", rank:40, winner:0.58,  flag:"py"     },
  "Norway":                { group:"I", rank:31, winner:0.57,  flag:"no"     },
  "Ivory Coast":           { group:"E", rank:34, winner:0.49,  flag:"ci"     },
  "Iraq":                  { group:"I", rank:57, winner:0.49,  flag:"iq"     },
  "South Africa":          { group:"A", rank:60, winner:0.48,  flag:"za"     },
  "Sweden":                { group:"F", rank:38, winner:0.43,  flag:"se"     },
  "Panama":                { group:"L", rank:33, winner:0.41,  flag:"pa"     },
  "Cape Verde":            { group:"H", rank:69, winner:0.37,  flag:"cv"     },
  "Jordan":                { group:"J", rank:63, winner:0.32,  flag:"jo"     },
  "Bosnia and Herzegovina":{ group:"B", rank:65, winner:0.29,  flag:"ba"     },
  "Ghana":                 { group:"L", rank:74, winner:0.19,  flag:"gh"     },
  "Saudi Arabia":          { group:"H", rank:61, winner:0.15,  flag:"sa"     },
  "Curacao":               { group:"E", rank:82, winner:0.13,  flag:"cw"     },
  "Qatar":                 { group:"B", rank:55, winner:0.13,  flag:"qa"     },
  "New Zealand":           { group:"G", rank:85, winner:0.08,  flag:"nz"     },
  "Haiti":                 { group:"C", rank:83, winner:0.05,  flag:"ht"     }
};

// ─── FIXTURES (Group Stage only — 72 matches) ────────────────────────────────
const FIXTURES = [
  // ── GROUP A ──
  { id:1,  md:1, date:"Jun 11", home:"Mexico",       away:"South Africa",  group:"A", venue:"Estadio Azteca" },
  { id:2,  md:1, date:"Jun 11", home:"South Korea",  away:"Czech Republic",group:"A", venue:"Estadio Akron" },
  { id:28, md:2, date:"Jun 18", home:"Mexico",       away:"South Korea",   group:"A", venue:"Estadio Akron" },
  { id:25, md:2, date:"Jun 18", home:"Czech Republic",away:"South Africa", group:"A", venue:"Mercedes-Benz Stadium" },
  { id:53, md:3, date:"Jun 24", home:"Czech Republic",away:"Mexico",       group:"A", venue:"Estadio Azteca" },
  { id:54, md:3, date:"Jun 24", home:"South Africa", away:"South Korea",   group:"A", venue:"Estadio BBVA" },
  // ── GROUP B ──
  { id:3,  md:1, date:"Jun 12", home:"Canada",       away:"Bosnia and Herzegovina", group:"B", venue:"BMO Field Toronto" },
  { id:8,  md:1, date:"Jun 13", home:"Qatar",        away:"Switzerland",   group:"B", venue:"Levi's Stadium" },
  { id:27, md:2, date:"Jun 18", home:"Canada",       away:"Qatar",         group:"B", venue:"BC Place Vancouver" },
  { id:26, md:2, date:"Jun 18", home:"Switzerland",  away:"Bosnia and Herzegovina", group:"B", venue:"SoFi Stadium" },
  { id:51, md:3, date:"Jun 24", home:"Switzerland",  away:"Canada",        group:"B", venue:"BC Place Vancouver" },
  { id:52, md:3, date:"Jun 24", home:"Bosnia and Herzegovina",away:"Qatar",group:"B", venue:"Lumen Field Seattle" },
  // ── GROUP C ──
  { id:5,  md:1, date:"Jun 13", home:"Haiti",        away:"Scotland",      group:"C", venue:"Gillette Stadium" },
  { id:7,  md:1, date:"Jun 13", home:"Brazil",       away:"Morocco",       group:"C", venue:"MetLife Stadium" },
  { id:29, md:2, date:"Jun 19", home:"Brazil",       away:"Haiti",         group:"C", venue:"Lincoln Financial Field" },
  { id:30, md:2, date:"Jun 19", home:"Scotland",     away:"Morocco",       group:"C", venue:"Gillette Stadium" },
  { id:49, md:3, date:"Jun 24", home:"Scotland",     away:"Brazil",        group:"C", venue:"Hard Rock Stadium" },
  { id:50, md:3, date:"Jun 24", home:"Morocco",      away:"Haiti",         group:"C", venue:"Mercedes-Benz Stadium" },
  // ── GROUP D ──
  { id:4,  md:1, date:"Jun 12", home:"USA",          away:"Paraguay",      group:"D", venue:"SoFi Stadium" },
  { id:6,  md:1, date:"Jun 13", home:"Australia",    away:"Turkey",        group:"D", venue:"BC Place Vancouver" },
  { id:32, md:2, date:"Jun 19", home:"USA",          away:"Australia",     group:"D", venue:"Lumen Field Seattle" },
  { id:31, md:2, date:"Jun 19", home:"Turkey",       away:"Paraguay",      group:"D", venue:"Levi's Stadium" },
  { id:59, md:3, date:"Jun 25", home:"Turkey",       away:"USA",           group:"D", venue:"SoFi Stadium" },
  { id:60, md:3, date:"Jun 25", home:"Paraguay",     away:"Australia",     group:"D", venue:"Levi's Stadium" },
  // ── GROUP E ──
  { id:9,  md:1, date:"Jun 14", home:"Ivory Coast",  away:"Ecuador",       group:"E", venue:"Lincoln Financial Field" },
  { id:10, md:1, date:"Jun 14", home:"Germany",      away:"Curacao",       group:"E", venue:"NRG Stadium Houston" },
  { id:33, md:2, date:"Jun 20", home:"Germany",      away:"Ivory Coast",   group:"E", venue:"BMO Field Toronto" },
  { id:34, md:2, date:"Jun 20", home:"Ecuador",      away:"Curacao",       group:"E", venue:"Arrowhead Stadium" },
  { id:56, md:3, date:"Jun 25", home:"Ecuador",      away:"Germany",       group:"E", venue:"MetLife Stadium" },
  { id:55, md:3, date:"Jun 25", home:"Curacao",      away:"Ivory Coast",   group:"E", venue:"Lincoln Financial Field" },
  // ── GROUP F ──
  { id:11, md:1, date:"Jun 14", home:"Netherlands",  away:"Japan",         group:"F", venue:"AT&T Stadium" },
  { id:12, md:1, date:"Jun 14", home:"Sweden",       away:"Tunisia",       group:"F", venue:"Estadio BBVA" },
  { id:35, md:2, date:"Jun 20", home:"Netherlands",  away:"Sweden",        group:"F", venue:"NRG Stadium Houston" },
  { id:36, md:2, date:"Jun 20", home:"Tunisia",      away:"Japan",         group:"F", venue:"Estadio BBVA" },
  { id:57, md:3, date:"Jun 25", home:"Japan",        away:"Sweden",        group:"F", venue:"AT&T Stadium" },
  { id:58, md:3, date:"Jun 25", home:"Tunisia",      away:"Netherlands",   group:"F", venue:"Arrowhead Stadium" },
  // ── GROUP G ──
  { id:15, md:1, date:"Jun 15", home:"Iran",         away:"New Zealand",   group:"G", venue:"SoFi Stadium" },
  { id:16, md:1, date:"Jun 15", home:"Belgium",      away:"Egypt",         group:"G", venue:"Lumen Field Seattle" },
  { id:39, md:2, date:"Jun 21", home:"Belgium",      away:"Iran",          group:"G", venue:"SoFi Stadium" },
  { id:40, md:2, date:"Jun 21", home:"New Zealand",  away:"Egypt",         group:"G", venue:"BC Place Vancouver" },
  { id:63, md:3, date:"Jun 26", home:"Egypt",        away:"Iran",          group:"G", venue:"Lumen Field Seattle" },
  { id:64, md:3, date:"Jun 26", home:"New Zealand",  away:"Belgium",       group:"G", venue:"BC Place Vancouver" },
  // ── GROUP H ──
  { id:13, md:1, date:"Jun 15", home:"Saudi Arabia", away:"Uruguay",       group:"H", venue:"Hard Rock Stadium" },
  { id:14, md:1, date:"Jun 15", home:"Spain",        away:"Cape Verde",    group:"H", venue:"Mercedes-Benz Stadium" },
  { id:37, md:2, date:"Jun 21", home:"Uruguay",      away:"Cape Verde",    group:"H", venue:"Hard Rock Stadium" },
  { id:38, md:2, date:"Jun 21", home:"Spain",        away:"Saudi Arabia",  group:"H", venue:"Mercedes-Benz Stadium" },
  { id:65, md:3, date:"Jun 26", home:"Cape Verde",   away:"Saudi Arabia",  group:"H", venue:"NRG Stadium Houston" },
  { id:66, md:3, date:"Jun 26", home:"Uruguay",      away:"Spain",         group:"H", venue:"Estadio Akron" },
  // ── GROUP I ──
  { id:17, md:1, date:"Jun 16", home:"France",       away:"Senegal",       group:"I", venue:"MetLife Stadium" },
  { id:18, md:1, date:"Jun 16", home:"Iraq",         away:"Norway",        group:"I", venue:"Gillette Stadium" },
  { id:42, md:2, date:"Jun 22", home:"France",       away:"Iraq",          group:"I", venue:"Lincoln Financial Field" },
  { id:41, md:2, date:"Jun 22", home:"Norway",       away:"Senegal",       group:"I", venue:"MetLife Stadium" },
  { id:61, md:3, date:"Jun 26", home:"Norway",       away:"France",        group:"I", venue:"Gillette Stadium" },
  { id:62, md:3, date:"Jun 26", home:"Senegal",      away:"Iraq",          group:"I", venue:"BMO Field Toronto" },
  // ── GROUP J ──
  { id:19, md:1, date:"Jun 16", home:"Argentina",    away:"Algeria",       group:"J", venue:"Arrowhead Stadium" },
  { id:20, md:1, date:"Jun 16", home:"Austria",      away:"Jordan",        group:"J", venue:"Levi's Stadium" },
  { id:43, md:2, date:"Jun 22", home:"Argentina",    away:"Austria",       group:"J", venue:"AT&T Stadium" },
  { id:44, md:2, date:"Jun 22", home:"Jordan",       away:"Algeria",       group:"J", venue:"Levi's Stadium" },
  { id:70, md:3, date:"Jun 27", home:"Jordan",       away:"Argentina",     group:"J", venue:"AT&T Stadium" },
  { id:69, md:3, date:"Jun 27", home:"Algeria",      away:"Austria",       group:"J", venue:"Arrowhead Stadium" },
  // ── GROUP K ──
  { id:23, md:1, date:"Jun 17", home:"Portugal",     away:"DR Congo",      group:"K", venue:"NRG Stadium Houston" },
  { id:24, md:1, date:"Jun 17", home:"Uzbekistan",   away:"Colombia",      group:"K", venue:"Estadio Azteca" },
  { id:47, md:2, date:"Jun 23", home:"Portugal",     away:"Uzbekistan",    group:"K", venue:"NRG Stadium Houston" },
  { id:48, md:2, date:"Jun 23", home:"Colombia",     away:"DR Congo",      group:"K", venue:"Estadio Akron" },
  { id:71, md:3, date:"Jun 27", home:"Colombia",     away:"Portugal",      group:"K", venue:"Hard Rock Stadium" },
  { id:72, md:3, date:"Jun 27", home:"DR Congo",     away:"Uzbekistan",    group:"K", venue:"Mercedes-Benz Stadium" },
  // ── GROUP L ──
  { id:21, md:1, date:"Jun 17", home:"Ghana",        away:"Panama",        group:"L", venue:"BMO Field Toronto" },
  { id:22, md:1, date:"Jun 17", home:"England",      away:"Croatia",       group:"L", venue:"AT&T Stadium" },
  { id:45, md:2, date:"Jun 23", home:"England",      away:"Ghana",         group:"L", venue:"Gillette Stadium" },
  { id:46, md:2, date:"Jun 23", home:"Panama",       away:"Croatia",       group:"L", venue:"BMO Field Toronto" },
  { id:67, md:3, date:"Jun 27", home:"Panama",       away:"England",       group:"L", venue:"MetLife Stadium" },
  { id:68, md:3, date:"Jun 27", home:"Croatia",      away:"Ghana",         group:"L", venue:"Lincoln Financial Field" }
];
